---
version: 2
project_name: aws-probe
dist: ./dist/

force_token: github
env_files:
  gitea_token: ~/nope
  github_token: ~/nope

release:
  disable: false
  skip_upload: false
  github:
    owner: xenos76
    name: aws-probe

before:
  hooks:
    - go mod download
    - go mod tidy
    - go test ./...
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run . completion bash > completions/aws-probe.bash'
    - sh -c 'go run . completion zsh > completions/aws-probe.zsh'
    - sh -c 'go run . completion fish > completions/aws-probe.fish'

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/xenos76/aws-probe/internal/cmd.Version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_{{- .Version }}_{{- title .Os }}_{{- .Arch }}
    wrap_in_directory: false
    formats:
      - tar.gz
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

nfpms:
  - maintainer: Zeno Belli <xeno@os76.xyz>
    vendor: xenos76 on Github
    homepage: https://github.com/xenOs76/aws-probe
    description: aws-probe, a tool for checking cloud wiring
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: completions/aws-probe.bash
        dst: /etc/bash_completion.d/aws-probe
      - src: completions/aws-probe.fish
        dst: /usr/share/fish/vendor_completions.d/aws-probe.fish
      - src: completions/aws-probe.zsh
        dst: /usr/share/zsh/site-functions/_aws-probe
    release: "1"

homebrew_casks:
  - repository:
      owner: xenos76
      name: homebrew-tap
    homepage: https://github.com/xenOs76/aws-probe
    description: aws-probe, a tool for checking cloud wiring
    license: MIT
    skip_upload: false
    completions:
      bash: "completions/{{ .ProjectName }}.bash"
      zsh: "completions/{{ .ProjectName }}.zsh"
      fish: "completions/{{ .ProjectName }}.fish"

nix:
  - name: aws-probe
    repository:
      owner: xenos76
      name: nur-packages
    homepage: https://github.com/xenOs76/aws-probe
    description: aws-probe
    path: pkgs/aws-probe/default.nix
    license: mit
    extra_install: |-
      installShellCompletion --cmd aws-probe \
        --bash <($out/bin/aws-probe completion bash) \
        --fish <($out/bin/aws-probe completion fish) \
        --zsh <($out/bin/aws-probe completion zsh)

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
