---
name: CodeChecks
on:
  push:
    paths:
      - ".github/workflows/codeChecks.yml"
      - ".goreleaser.yaml"
      - ".testcoverage.yml"
      - "internal/**"
      - "*.go"
      - "go.*"

jobs:
  go_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to checkout and read repo files
      security-events: write # Required to upload SARIF files to Security tab

    strategy:
      max-parallel: 1
      matrix:
        go-version: ["1.25"]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test -v ./...

      - name: Check for vulnerabilities
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ matrix.go-version }}
          go-package: ./...
          work-dir: .

  # go_test_coverage_check:
  #   needs: go_tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: actions/setup-go@v6
  #       with:
  #         go-version: "1.25"
  #
  #     - name: generate test coverage
  #       run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
  #
  #     - name: check test coverage
  #       continue-on-error: ${{ github.ref_name != 'main' }}
  #       uses: vladopajic/go-test-coverage@v2
  #       with:
  #         config: ./.testcoverage.yml
  #         git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
  #         git-branch: badges
